
platform :ios, '14.1'
workspace 'Supplements'
target 'Supplements' do
  use_frameworks! :linkage => :static
  pod 'SnapKit'
  pod 'GoogleSignIn'
  pod 'Onboard'
  pod 'CollectionViewPagingLayout'
  pod 'Alamofire'
  pod 'LinearProgressView'
  pod 'JTAppleCalendar'
  pod 'FSCalendar'
  pod 'CalendarHeatmap'
  pod 'Popover'
  pod 'SwipeableTabBarController'
  pod 'SwiftyJSON'

end
